import { Montserrat, Roboto } from 'next/font/google';
import "./globals.css";
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';
import { Toaster } from '@/components/ui/toaster';

const montserrat = Montserrat({
  subsets: ['latin'], // Include the subset needed for your project
  variable: '--font-montserrat', // Define a CSS variable
  weight: ['400', '700'], // Define specific weights (normal and bold)
});

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['400', '500'], // Add weights you use for body text
});


export const metadata = {
  title: "Infraestructura y Senalizacion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.variable} ${roboto.variable}`}>
      <body className='flex flex-col'>
        <NavBar />
        {children}
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
